# Site settings
title: 逆行云的技术博客
email: yuqiang.coder@gamil.com
description: 世界上有10种人, 一种是懂二进制的人, 一种是不懂二进制的人.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
# url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
#twitter_username: ""
github_username:  YQqiang

# Build settings
#markdown: kramdown
permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: 逆行云
  email: yuqiang.coder@gmail.com
  link:  ""
  weibo: ""
  github: https://github.com/YQqiang
title: 逆行云的技术博客                             #自定义常量

# avatar头像及Favicon
avatar: https://github.com/YQqiang/YQqiang.github.io/blob/master/assets/images/mine.JPG?raw=true
#favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: kramdown                         #markdown解释器

# google analytics 设置
#ga:
#  id:
#  url:
#

# baidu analytics 设置

ba:
  src: //hm.baidu.com/hm.js?22d94317cfb9f9e0bb476228d9f79278

# disqus 设置
disqus:
  shortname: yuqiangCoder
